[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -DDEBUG
lib_deps =
    adafruit/Adafruit GFX Library

[env:rp2350]
; Target MCU — Waveshare RP2350-Zero (same chip as Pico 2)
platform = raspberrypi
board = rpipico2
framework = arduino
monitor_speed = 115200
