#!/usr/bin/env python3
"""
Generate src/display/CompassFrames.h
16 pre-rendered BWFramebuffer images, one per 22.5-degree compass heading.
Replicates BWRenderer::render() and BWFramebuffer pixel routines exactly.
Run from the pod/ directory: python scripts/gen_compass_frames.py
"""

import math, os

BW_WIDTH     = 250
BW_HEIGHT    = 122
BW_ROW_BYTES = (BW_WIDTH + 7) // 8  # 32
BW_BUF_SIZE  = BW_ROW_BYTES * BW_HEIGHT  # 3904

CX = BW_WIDTH // 2  # 125
CY = 38
CR = 32


def make_buf():
    return bytearray(b'\xff' * BW_BUF_SIZE)  # white background


def set_pixel(buf, x, y, white=False):
    if 0 <= x < BW_WIDTH and 0 <= y < BW_HEIGHT:
        idx = y * BW_ROW_BYTES + x // 8
        bit = 7 - (x % 8)
        if white:
            buf[idx] |=  (1 << bit)
        else:
            buf[idx] &= ~(1 << bit)


def draw_line(buf, x0, y0, x1, y1, white=False):
    """Bresenham line — matches BWFramebuffer::drawLine exactly."""
    dx = abs(x1 - x0); sx = 1 if x0 < x1 else -1
    dy = -abs(y1 - y0); sy = 1 if y0 < y1 else -1
    err = dx + dy
    while True:
        set_pixel(buf, x0, y0, white)
        if x0 == x1 and y0 == y1:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy; x0 += sx
        if e2 <= dx:
            err += dx; y0 += sy


def draw_circle(buf, cx, cy, r, white=False):
    """Midpoint circle — matches BWFramebuffer::drawCircle exactly."""
    x, y, err = r, 0, 0
    while x >= y:
        for px, py in [
            (cx+x, cy+y), (cx+y, cy+x),
            (cx-y, cy+x), (cx-x, cy+y),
            (cx-x, cy-y), (cx-y, cy-x),
            (cx+y, cy-x), (cx+x, cy-y),
        ]:
            set_pixel(buf, px, py, white)
        if err <= 0:
            y += 1; err += 2 * y + 1
        else:
            x -= 1; err -= 2 * x + 1


def render_compass(heading_deg):
    """Matches BWRenderer::render() for a valid (non-NaN) heading."""
    buf = make_buf()

    draw_circle(buf, CX, CY, CR)

    # Tick marks — long at cardinals (N/E/S/W), short at intermediates
    for d in range(0, 360, 45):
        rad = d * math.pi / 180.0
        ln = 7 if d % 90 == 0 else 4
        x0 = CX + int((CR - ln) * math.sin(rad))
        y0 = CY - int((CR - ln) * math.cos(rad))
        x1 = CX + int(CR * math.sin(rad))
        y1 = CY - int(CR * math.cos(rad))
        draw_line(buf, x0, y0, x1, y1)

    # Forward needle — thick (3 adjacent lines)
    rad = heading_deg * math.pi / 180.0
    s, c = math.sin(rad), math.cos(rad)
    nx = CX + int((CR - 6) * s)
    ny = CY - int((CR - 6) * c)
    draw_line(buf, CX,   CY,   nx,   ny)
    draw_line(buf, CX+1, CY,   nx+1, ny)
    draw_line(buf, CX,   CY+1, nx,   ny+1)

    # Back stub
    bx = CX - int((CR // 3) * s)
    by = CY + int((CR // 3) * c)
    draw_line(buf, CX, CY, bx, by)

    # Divider line below compass rose
    draw_line(buf, 4, CY + CR + 8, BW_WIDTH - 4, CY + CR + 8)

    return buf


def main():
    frames = [render_compass(i * 22.5) for i in range(16)]

    lines = [
        '// Auto-generated by scripts/gen_compass_frames.py — do not edit.',
        '// 16 pre-rendered compass frames at 22.5-degree steps.',
        '// Index 0 = North (0 deg), 1 = NNE (22.5 deg), ..., 15 = NNW (337.5 deg).',
        '#pragma once',
        '#include "BWFramebuffer.h"',
        '',
        'static const uint8_t COMPASS_FRAMES[16][BW_BUF_SIZE] = {',
    ]

    for i, buf in enumerate(frames):
        heading = i * 22.5
        lines.append(f'    // [{i:2d}]  {heading:.1f} deg')
        hex_vals = ', '.join(f'0x{b:02X}' for b in buf)
        lines.append(f'    {{ {hex_vals} }},')

    lines += [
        '};',
    ]

    out_path = os.path.join(os.path.dirname(__file__),
                            '..', 'src', 'display', 'CompassFrames.h')
    out_path = os.path.normpath(out_path)
    with open(out_path, 'w', newline='\n') as f:
        f.write('\n'.join(lines) + '\n')

    total = BW_BUF_SIZE * 16
    print(f'Written {total} bytes across 16 frames to {out_path}')


if __name__ == '__main__':
    main()
